// Development-only verification. Never used by index.html or GitHub Pages.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=process.env.YVM_TEST_OUTPUT||path.join(root,'test-results');fs.mkdirSync(out,{recursive:true});
const results=[],errors=[],requests=[];let browser,server;
const check=(name,fn)=>Promise.resolve().then(fn).then(()=>{results.push(name);console.log('PASS',name);});
const fileURL=p=>'file:///'+p.replace(/\\/g,'/');
async function download(page,selector,name,quality=false){await page.locator(selector).click();if(quality){await page.locator('#quality-export').waitFor();const event=page.waitForEvent('download');await page.locator('#quality-export').click();await(await event).saveAs(path.join(out,name));}else{throw new Error('Use downloadDirect for immediate downloads');}}
async function downloadDirect(page,selector,name){const event=page.waitForEvent('download');await page.locator(selector).first().click();await(await event).saveAs(path.join(out,name));}
function zipEntries(buffer){const entries=[];let offset=0;while(buffer.readUInt32LE(offset)===0x04034b50){const size=buffer.readUInt32LE(offset+18),n=buffer.readUInt16LE(offset+26),extra=buffer.readUInt16LE(offset+28),name=buffer.subarray(offset+30,offset+30+n).toString();const start=offset+30+n+extra;entries.push({name,bytes:buffer.subarray(start,start+size)});offset=start+size;}return entries;}
(async()=>{
 browser=await chromium.launch({headless:true,channel:process.env.YVM_BROWSER_CHANNEL||'chrome'});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
 context.on('page',page=>{page.on('pageerror',err=>errors.push(err.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});page.on('request',req=>requests.push(req.url()));});
 const page=await context.newPage();await page.goto(fileURL(path.join(root,'index.html')));await page.locator('#close-modal').click();
 await check('Home loads from file://, 6 samples, no external libraries',async()=>{assert.equal(await page.locator('[data-sample]').count(),6);assert.equal(await page.title(),'엽쌤스쿨 영상제작기');assert.ok(await page.locator('#new-project').isVisible());});
 await page.screenshot({path:path.join(out,'home-desktop.png'),fullPage:true});
 await page.locator('#new-project').click();
 await check('Wizard validation prevents generation without input',async()=>{await page.locator('[data-step="5"]').click();await page.locator('#generate').click();assert.ok(await page.locator('[data-project="title"]').isVisible());assert.equal(await page.locator('[data-scene]').count(),0);});
 await page.locator('[data-project="title"]').fill('교실 미션');
 await check('Debounced auto-save while the title field retains focus',async()=>{await page.waitForTimeout(1200);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('yeopssam-projects-v1'))[0].title),'교실 미션');});
 await page.locator('[data-project="url"]').fill('https://example.org/classroom');await page.locator('[data-project="description"]').fill('함께 도전하고 기록하는 수업');
 await page.locator('[data-step="2"]').click();
 for(let i=0;i<3;i++)await page.locator(`[data-feature-input="${i}"]`).fill(['미션 선택','활동 기록','협력 활동'][i]);
 await page.locator('#feature-add').click();await page.locator('[data-feature-input="3"]').fill('성장 확인');await page.locator('#feature-add').click();await page.locator('[data-feature-input="4"]').fill('결과 공유');
 await check('Feature limit and order editing',async()=>{assert.ok(await page.locator('#feature-add').isDisabled());await page.locator('[data-feature-up="1"]').click();assert.equal(await page.locator('[data-feature-input="0"]').inputValue(),'활동 기록');});
 await page.locator('[data-step="3"]').click();
 // Create an actual PNG fixture with a DOM canvas, not an external image.
 const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=2400;c.height=1350;const x=c.getContext('2d');x.fillStyle='#dbe7fb';x.fillRect(0,0,c.width,c.height);x.fillStyle='#3867f4';x.fillRect(100,100,2200,350);x.fillStyle='#fff';x.font='bold 100px sans-serif';x.fillText('Classroom Missions',180,315);return c.toDataURL();});
 const imageFile=path.join(out,'fixture.png');fs.writeFileSync(imageFile,Buffer.from(png.split(',')[1],'base64'));
 await page.locator('#image-files').setInputFiles([imageFile,imageFile]);
 await check('Multiple image upload, WebP conversion, 1920px resize',async()=>{await page.waitForFunction(()=>YVM.store.get().images.length===2);const imgs=await page.evaluate(()=>YVM.store.get().images);assert.equal(imgs[0].width,1920);assert.ok(imgs[0].src.startsWith('data:image/webp;'));});
 await page.locator('[data-image-name]').first().fill('메인화면');await page.locator('[data-step="4"]').click();await page.locator('[data-style="Minimal"]').click();
 await page.locator('[data-step="5"]').click();await page.locator('#generate').click();
 await check('60-second generator creates nine contiguous scenes and fifth feature',async()=>{const p=await page.evaluate(()=>YVM.store.get());assert.equal(p.duration,60);assert.equal(p.scenes.length,9);assert.equal(p.scenes[0].start,0);assert.equal(p.scenes.at(-1).end,60);assert.ok(p.scenes[6].narration.includes('결과 공유'));for(let i=1;i<p.scenes.length;i++)assert.equal(p.scenes[i].start,p.scenes[i-1].end);});
 await check('Playback, pause, seek, mute, captions, restart and fullscreen',async()=>{await page.locator('.vp-play').click();await page.waitForTimeout(1300);assert.ok(await page.evaluate(()=>YVM.player.position())>=1);await page.locator('.vp-play').click();const t=await page.evaluate(()=>YVM.player.position());await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>YVM.player.position()),t);await page.locator('.vp-forward').click();assert.ok(await page.evaluate(()=>YVM.player.position())>=11);await page.locator('.vp-back').click();assert.ok(await page.evaluate(()=>YVM.player.position())<2);await page.locator('.vp-mute').click();assert.equal(await page.locator('.vp-mute').getAttribute('aria-pressed'),'true');await page.locator('.vp-subtoggle').click();assert.ok(await page.locator('.vp-subtitle').isHidden());await page.locator('.vp-subtoggle').click();await page.locator('.vp-full').click();assert.ok(await page.evaluate(()=>!!document.fullscreenElement));await page.evaluate(()=>document.exitFullscreen());await page.locator('.vp-reset').click();assert.equal(await page.evaluate(()=>YVM.player.position()),0);});
 await check('Scene text and duration edits propagate to preview and timeline',async()=>{await page.locator('[data-scene-field="caption"]').fill('우리 교실의 새로운 도전');await page.locator('[data-scene-field="narration"]').fill('우리 교실에서 함께 도전해 보세요.');await page.locator('[data-scene-field="duration"]').fill('6.5');await page.locator('[data-scene-field="caption"]').click();assert.equal(await page.evaluate(()=>YVM.store.get().duration),61.5);assert.equal(await page.locator('.vp-caption').textContent(),'우리 교실의 새로운 도전');});
 await check('Undo/redo and keyboard shortcuts',async()=>{await page.locator('#undo').click();assert.equal(await page.evaluate(()=>YVM.store.get().scenes[0].duration),5);await page.locator('#redo').click();assert.equal(await page.evaluate(()=>YVM.store.get().scenes[0].duration),6.5);await page.locator('.scene-item').first().focus();await page.keyboard.press('Control+d');assert.equal(await page.locator('[data-scene]').count(),10);await page.locator('.scene-item').first().focus();await page.keyboard.press('Delete');assert.equal(await page.locator('[data-scene]').count(),9);await page.locator('#scene-add').click();assert.equal(await page.locator('[data-scene]').count(),10);await page.locator('#scene-delete').click();assert.equal(await page.locator('[data-scene]').count(),9);});
 await check('Drag reorder and scene image replacement',async()=>{const before=await page.evaluate(()=>YVM.store.get().scenes.map(s=>s.id));await page.locator('[data-scene]').nth(0).dragTo(page.locator('[data-scene]').nth(2));const after=await page.evaluate(()=>YVM.store.get().scenes.map(s=>s.id));assert.notDeepEqual(before,after);await page.locator('[data-scene]').first().click();await page.locator('[data-scene-field="imageId"]').selectOption({label:'이미지 없음 (타이포그래피)'});assert.ok(await page.locator('#image-prompt').isVisible());await page.locator('#image-prompt').click();assert.ok((await page.locator('dialog textarea').inputValue()).includes('16:9'));await page.locator('#close-modal').click();await page.locator('[data-scene-field="imageId"]').selectOption({index:1});});
 await check('All eight themes, thirteen image effects and six text effects render',async()=>{await page.evaluate(()=>{const p=YVM.store.get(),root=document.createElement('div');document.body.append(root);for(const t of YVM.catalog.templates){p.style=t.id;for(const a of YVM.catalog.presets.animations){p.scenes[0].animation=a;const player=YVM.playerRuntime(root,YVM.clone(p));player.seek(.5);player.destroy();}}for(const a of YVM.catalog.presets.textAnimations){p.scenes[0].textAnimation=a;const player=YVM.playerRuntime(root,YVM.clone(p));player.seek(.5);player.destroy();}root.remove();p.style='Minimal';p.scenes[0].animation='slowZoom';p.scenes[0].textAnimation='fade';});});
 await check('30, 45, 60, 90 second generator maintains exact contiguous timings',async()=>{const totals=await page.evaluate(()=>[30,45,60,90].map(d=>{const p=YVM.clone(YVM.store.get());p.targetDuration=d;YVM.generate(p);return [d,p.duration,p.scenes.every((s,i)=>s.start===(i?p.scenes[i-1].end:0)),p.scenes.at(-1).end];}));for(const [d,total,contiguous,end]of totals){assert.equal(d,total);assert.ok(contiguous);assert.equal(end,d);}});
 // Produce a local WAV for audio wiring (one-second PCM sine wave).
 const rate=8000,samples=8000,wav=Buffer.alloc(44+samples*2);wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(samples*2,40);for(let i=0;i<samples;i++)wav.writeInt16LE(Math.round(Math.sin(i/rate*440*Math.PI*2)*300),44+i*2);const audioFile=path.join(out,'tone.wav');fs.writeFileSync(audioFile,wav);
 await page.locator('.audio-settings summary').click();await page.locator('#bgm-file').setInputFiles(audioFile);await page.waitForFunction(()=>!!YVM.store.get().bgm);
 await page.locator('#sfx-file').setInputFiles(audioFile);await page.waitForFunction(()=>YVM.store.get().scenes.some(s=>s.sfx));
 await check('BGM and scene sound uploads preserved in project',async()=>{const p=await page.evaluate(()=>YVM.store.get());assert.ok(p.bgm.src.startsWith('data:audio/wav'));assert.ok(p.scenes.some(s=>s.sfx?.src.startsWith('data:audio/wav')));await page.locator('.vp-play').click();await page.waitForTimeout(500);await page.locator('.vp-play').click();});
 await check('Prompt tabs and Codex text output',async()=>{await page.locator('[data-tab="prompts"]').click();assert.equal(await page.locator('.prompt-card').count(),9);await page.locator('#codex-prompt').click();assert.ok((await page.locator('dialog textarea').inputValue()).includes('교실 미션'));await downloadDirect(page,'#prompt-download','codex-prompt.txt');await page.locator('#close-modal').click();});
 await check('SRT, narration, scenes and self-contained project downloads',async()=>{for(const name of ['subtitles-ko.srt','narration-ko.txt','scenes.json','project.json'])await downloadDirect(page,`[data-export="${name}"]`,name);const p=JSON.parse(fs.readFileSync(path.join(out,'project.json')));assert.equal(p.images.length,2);assert.ok(p.bgm.src.startsWith('data:'));assert.match(fs.readFileSync(path.join(out,'subtitles-ko.srt'),'utf8'),/00:00:00,000 -->/);assert.equal(JSON.parse(fs.readFileSync(path.join(out,'scenes.json'))).scenes.length,9);});
 await check('Project JSON import restores images, narration, audio and scenes',async()=>{const before=await page.evaluate(()=>YVM.clone(YVM.store.get()));await page.locator('.brand').click();await page.locator('#project-file').setInputFiles(path.join(out,'project.json'));await page.waitForSelector('#preview');const after=await page.evaluate(()=>YVM.store.get());assert.equal(after.scenes.length,before.scenes.length);assert.deepEqual(after.images,before.images);assert.deepEqual(after.bgm,before.bgm);});
 await check('Malformed and external-resource JSON rejected without changing project',async()=>{const invalid=path.join(out,'invalid.json');fs.writeFileSync(invalid,'{broken');const id=await page.evaluate(()=>YVM.store.get().id);await page.locator('#project-file').setInputFiles(invalid);await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>YVM.store.get().id),id);const error=await page.evaluate(()=>{try{const p=YVM.clone(YVM.store.get());p.images[0].src='https://example.com/image.png';YVM.validateProject(p);}catch(err){return err.message;}});assert.ok(error.includes('이미지'));});
 await check('ZIP package and standalone HTML downloads',async()=>{await download(page,'#header-zip','my-video.zip',true);await download(page,'[data-export="video.html"]','video.html',true);const entries=zipEntries(fs.readFileSync(path.join(out,'my-video.zip')));for(const required of ['index.html','style.css','app.js','data/scenes.json','subtitles/subtitles-ko.srt','scripts/narration-ko.txt','README.md','project.json'])assert.ok(entries.some(entry=>entry.name===required),required);assert.ok(entries.some(entry=>entry.name.startsWith('assets/images/')));assert.ok(entries.some(entry=>entry.name.startsWith('assets/audio/')));for(const entry of entries){const target=path.join(out,'unzipped',entry.name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,entry.bytes);}});
 await check('Standalone HTML runs offline with embedded images and live timeline',async()=>{const video=await context.newPage();await video.goto(fileURL(path.join(out,'video.html')));await video.waitForTimeout(1300);assert.match(await video.locator('.vp-time').textContent(),/00:01/);const loaded=await video.evaluate(async()=>{const src=document.querySelector('.vp-image').style.backgroundImage.match(/url\("?(.*?)"?\)/)?.[1];const img=new Image();img.src=src;try{await img.decode();return img.naturalWidth;}catch{return 0;}});assert.ok(loaded>0);await video.close();});
 await check('Extracted ZIP runs with relative image and audio assets from file://',async()=>{const video=await context.newPage();await video.goto(fileURL(path.join(out,'unzipped/index.html')));await video.waitForTimeout(1200);assert.ok((await video.locator('.vp-caption').textContent()).length>0);assert.match(await video.locator('.vp-time').textContent(),/00:01/);await video.close();});
 await page.locator('[data-tab="summary"]').click();await page.evaluate(()=>document.querySelector('#toasts').replaceChildren());await page.screenshot({path:path.join(out,'editor-desktop.png'),fullPage:true});
 await check('Tablet and mobile layouts have no horizontal page overflow',async()=>{for(const width of [1024,768,390]){await page.setViewportSize({width,height:1000});await page.waitForTimeout(60);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),`overflow at ${width}`);assert.ok(await page.locator('#preview').isVisible());if(width===1024)await page.screenshot({path:path.join(out,'editor-tablet.png'),fullPage:true});}});
 await page.setViewportSize({width:1440,height:1000});
 await check('Dashboard persists, duplicates, exports and deletes saved projects',async()=>{await page.locator('#save-local').click();await page.locator('.brand').click();const n=await page.locator('[data-open]').count();assert.ok(n>=1);await page.locator('[data-duplicate]').first().click();assert.equal(await page.locator('[data-open]').count(),n+1);await downloadDirect(page,'[data-project-export]','dashboard-project.json');await page.locator('[data-delete]').first().click();await page.locator('#delete-confirm').click();assert.equal(await page.locator('[data-open]').count(),n);await page.reload();assert.equal(await page.locator('[data-open]').count(),n);});
 await check('All six sample projects open, render valid images and can export',async()=>{for(const slug of ['sweat-drop','hangul-day','old-game','asian-game','history','acappella']){await page.locator(`[data-sample="${slug}"]`).click();await page.waitForSelector('#preview');const loaded=await page.evaluate(async()=>{const imgs=Array.from(document.querySelectorAll('.scene-item img'));await Promise.all(imgs.map(img=>img.decode()));return imgs.every(img=>img.naturalWidth>0);});assert.ok(loaded);assert.equal(await page.locator('[data-scene]').count(),9);await page.locator('.brand').click();}});
 await check('Undo history retains at least 30 scene changes',async()=>{await page.locator('[data-sample="sweat-drop"]').click();const state=await page.evaluate(()=>{for(let i=0;i<35;i++)YVM.store.change(p=>p.scenes[0].caption='Edit '+i,{render:false});for(let i=0;i<30;i++)YVM.store.undo();return YVM.store.get().scenes[0].caption;});assert.equal(state,'Edit 4');await page.locator('.brand').click();});
 // Serve unchanged static files under a repository subpath to simulate Pages, never an app backend.
 server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]);let relative=url.replace(/^\/Making-Film\//,'');if(url==='/Making-Film/'||url==='/Making-Film')relative='index.html';const target=path.resolve(root,relative);if(!target.startsWith(root+path.sep)&&target!==root){res.writeHead(403).end();return;}if(!fs.existsSync(target)){res.writeHead(404).end();return;}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.json':'application/json'}[path.extname(target)]||'application/octet-stream';res.setHeader('Content-Type',mime);res.end(fs.readFileSync(target));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 const hosted=await context.newPage(),base=`http://127.0.0.1:${server.address().port}/Making-Film/`;
 await check('GitHub Pages subpath static serving, relative files and hash navigation',async()=>{await hosted.goto(base);await hosted.locator('#close-modal').click();await hosted.locator('[data-sample="history"]').click();await hosted.waitForSelector('#preview');await hosted.locator('.vp-play').click();await hosted.waitForTimeout(1100);assert.ok((await hosted.locator('.vp-time').textContent()).startsWith('00:01'));await hosted.locator('#save-local').click();await hosted.reload();await hosted.locator('[data-open]').first().click();await hosted.waitForSelector('#preview');});
 await check('Storage failure is visible and JSON export still works',async()=>{await hosted.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('quota exceeded','QuotaExceededError');};YVM.store.save();});assert.match(await hosted.locator('#save-status').textContent(),/JSON/);await downloadDirect(hosted,'[data-export="project.json"]','quota-fallback.json');});
 await check('Playback reaches the final frame and stops',async()=>{await hosted.evaluate(()=>{YVM.player.seek(YVM.store.get().duration-.1);YVM.player.play();});await hosted.waitForTimeout(250);assert.equal(await hosted.evaluate(()=>YVM.player.isPlaying()),false);assert.equal(await hosted.evaluate(()=>YVM.player.position()),await hosted.evaluate(()=>YVM.store.get().duration));});
 await check('Text content remains inert inside standalone HTML export',async()=>{const html=await hosted.evaluate(()=>{const p=YVM.clone(YVM.store.get());p.scenes[0].caption='</script><script>globalThis.exportInjection=true</script>';p.url='javascript:alert(1)';return YVM.exportHTML(p);});const inert=await context.newPage();await inert.setContent(html);await inert.waitForTimeout(100);assert.equal(await inert.evaluate(()=>globalThis.exportInjection),undefined);assert.equal(await inert.locator('.app-link').count(),0);await inert.close();});
 await check('Corrupt local project entries do not break the dashboard',async()=>{const isolated=await browser.newContext();await isolated.addInitScript(()=>localStorage.setItem('yeopssam-projects-v1','[{}]'));const corrupt=await isolated.newPage();let fatal=false;corrupt.on('pageerror',()=>fatal=true);await corrupt.goto(fileURL(path.join(root,'index.html')));assert.equal(fatal,false);await corrupt.locator('#close-modal').click();assert.ok(await corrupt.locator('#new-project').isVisible());await isolated.close();});
 await check('No third-party requests or fatal console/page errors',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(requests.filter(url=>/^https?:/.test(url)&&!url.startsWith('http://127.0.0.1:')),[]);});
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({date:new Date().toISOString(),passed:results.length,checks:results,errors,thirdPartyRequests:requests.filter(url=>/^https?:/.test(url)&&!url.startsWith('http://127.0.0.1:'))},null,2));
 console.log(`${results.length} checks passed; ${errors.length} errors.`);
})().catch(error=>{console.error(error);fs.writeFileSync(path.join(out,'failure.txt'),error.stack||String(error));process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
