const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),zlib=require('zlib');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=process.env.YVM_TEST_OUTPUT||path.join(root,'test-results/prd');fs.mkdirSync(out,{recursive:true});
const results=[],errors=[],external=[];let browser;
const check=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name);};
const url=p=>'file:///'+p.replace(/\\/g,'/');
const text='프로젝트명: 별빛 퀴즈\n한 줄 소개: 학생들이 함께 퀴즈를 풀고 배움을 확인하는 교실 도구\n웹앱 분야: 놀이\n교과: 사회\n학년: 3~4학년\n대상: 교사, 학생\n영상 길이: 45초\n\n핵심 기능\n주제별 퀴즈 선택\n팀별 문제 풀이\n결과 확인\n\n향후 기능\nAI 문제 생성';
const escape=s=>s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
function docx(text){return `<?xml version="1.0" encoding="UTF-8"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${text.split('\n').map(line=>`<w:p><w:r><w:t>${escape(line)}</w:t></w:r></w:p>`).join('')}</w:body></w:document>`;}
function hwpx(text){return `<?xml version="1.0" encoding="UTF-8"?><hs:sec xmlns:hs="http://www.hancom.co.kr/hwpml/2011/section" xmlns:hp="http://www.hancom.co.kr/hwpml/2011/paragraph">${text.split('\n').map(line=>`<hp:p><hp:run><hp:t>${escape(line)}</hp:t></hp:run></hp:p>`).join('')}</hs:sec>`;}
const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc(bytes){let n=0xffffffff;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return(n^0xffffffff)>>>0;}
function zip(files,deflate=true){const local=[],central=[];let offset=0,centralSize=0;for(const [name,raw]of Object.entries(files)){const bytes=Buffer.from(raw),encoded=Buffer.from(name),content=deflate?zlib.deflateRawSync(bytes):bytes,l=Buffer.alloc(30),c=Buffer.alloc(46),sum=crc(bytes);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(20,4);l.writeUInt16LE(0x800,6);l.writeUInt16LE(deflate?8:0,8);l.writeUInt32LE(sum,14);l.writeUInt32LE(content.length,18);l.writeUInt32LE(bytes.length,22);l.writeUInt16LE(encoded.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt16LE(0x800,8);c.writeUInt16LE(deflate?8:0,10);c.writeUInt32LE(sum,16);c.writeUInt32LE(content.length,20);c.writeUInt32LE(bytes.length,24);c.writeUInt16LE(encoded.length,28);c.writeUInt32LE(offset,42);local.push(l,encoded,content);central.push(c,encoded);offset+=l.length+encoded.length+content.length;centralSize+=c.length+encoded.length;}const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(centralSize,12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,...central,end]);}
const fixtures={
 'quiz.txt':Buffer.from(text),'quiz.md':Buffer.from('# 별빛 퀴즈 PRD\n'+text.replace('핵심 기능\n','## 핵심 기능\n').replace('향후 기능\n','## 향후 기능\n')),
 'quiz.json':Buffer.from(JSON.stringify({project:{title:'별빛 퀴즈',description:'학생들이 함께 퀴즈를 풀고 배움을 확인하는 교실 도구',features:['주제별 퀴즈 선택','팀별 문제 풀이','결과 확인'],duration:45,grade:'3~4학년',subject:'사회',audience:['교사','학생'],category:'놀이'}})),
 'quiz.docx':zip({'[Content_Types].xml':'<Types/>','word/document.xml':docx(text)}),
 'quiz.hwpx':zip({'Contents/section1.xml':hwpx('핵심 기능\n주제별 퀴즈 선택\n팀별 문제 풀이\n결과 확인\n향후 기능\nAI 문제 생성'),'Contents/section0.xml':hwpx(text.split('\n\n핵심 기능')[0])}),
 'stored.docx':zip({'word/document.xml':docx(text)},false),'linebreak.docx':zip({'word/document.xml':docx(text).replace(/<\/w:t><\/w:r><\/w:p><w:p><w:r><w:t>/g,'</w:t><w:br/><w:t>')}),'utf16.txt':Buffer.concat([Buffer.from([0xff,0xfe]),Buffer.from(text,'utf16le')]),
 'broken.docx':Buffer.from('broken zip document'),'empty.txt':Buffer.from(''),'file.pdf':Buffer.from('%PDF-1.0 invalid file')
};Object.entries(fixtures).forEach(([name,bytes])=>fs.writeFileSync(path.join(out,name),bytes));
async function getDownload(page,selector,name){const wait=page.waitForEvent('download');await page.locator(selector).first().click();await(await wait).saveAs(path.join(out,name));}
(async()=>{
 browser=await chromium.launch({headless:true,channel:process.env.YVM_BROWSER_CHANNEL||'chrome'});
 const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
 context.on('page',page=>{page.on('pageerror',err=>errors.push(err.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});page.on('request',req=>{if(/^https?:/.test(req.url()))external.push(req.url());});});
 const page=await context.newPage();await page.goto(url(path.join(root,'index.html')));await page.locator('#close-modal').click();
 await check('PRD entry is available from home and the first Wizard step',async()=>{assert.ok(await page.locator('#prd-new').isVisible());await page.locator('#new-project').click();await page.locator('#prd-import').waitFor();await page.locator('#prd-import').click();assert.ok(await page.locator('#prd-text').isVisible());});
 await check('Short or empty pasted text is rejected without creating a project',async()=>{await page.locator('#prd-analyze').click();assert.match(await page.locator('#prd-error').textContent(),/20자/);assert.ok(await page.locator('#prd-result').isHidden());});
 await check('Pasted PRD extracts metadata, three features and 45 seconds',async()=>{await page.locator('#prd-text').fill(text);await page.locator('#prd-analyze').click();assert.equal(await page.locator('#prd-title').inputValue(),'별빛 퀴즈');assert.equal(await page.locator('#prd-duration').inputValue(),'45');assert.equal(await page.locator('#prd-features').inputValue(),'주제별 퀴즈 선택\n팀별 문제 풀이\n결과 확인');assert.equal(await page.locator('#prd-grade').inputValue(),'3~4학년');assert.equal(await page.locator('[data-prd-audience]:checked').count(),2);await page.screenshot({path:path.join(out,'prd-analysis.png')});});
 await check('Image-free generation, immediate save, playback and regeneration',async()=>{await page.locator('#prd-create').click();await page.waitForSelector('#preview');assert.equal(await page.locator('[data-scene]').count(),9);const p=await page.evaluate(()=>YVM.store.get());assert.equal(p.images.length,0);assert.equal(p.duration,45);assert.ok(p.prd);assert.ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('yeopssam-projects-v1')).some(p=>p.prd)));await page.locator('.vp-play').click();await page.waitForTimeout(1150);assert.match(await page.locator('.vp-time').textContent(),/00:01/);await page.locator('.vp-play').click();await page.locator('#generate').click();assert.equal(await page.locator('[data-scene]').count(),9);});
 await check('Source provenance and missing screenshot notice are visible',async()=>assert.match(await page.locator('#result-panel').textContent(),/PRD에서 만든 영상 초안/));
 await check('SRT and self-contained PRD project roundtrip',async()=>{await getDownload(page,'[data-export="project.json"]','prd-project.json');await getDownload(page,'[data-export="subtitles-ko.srt"]','prd-subtitles.srt');const p=JSON.parse(fs.readFileSync(path.join(out,'prd-project.json')));assert.equal(p.images.length,0);assert.equal(p.prd.filename,'붙여넣은 PRD');assert.equal(p.prd.text,undefined);await page.locator('#project-file').setInputFiles(path.join(out,'prd-project.json'));await page.waitForSelector('#preview');assert.equal(await page.evaluate(()=>YVM.store.get().duration),45);assert.equal(await page.evaluate(()=>YVM.store.get().grade),'3~4학년');});
 await check('PRD-only standalone HTML and ZIP export work with zero image assets',async()=>{await page.locator('[data-export="video.html"]').click();await getDownload(page,'#quality-export','prd-video.html');await page.locator('#export-zip').click();await getDownload(page,'#quality-export','prd-video.zip');const video=await context.newPage();await video.goto(url(path.join(out,'prd-video.html')));await video.waitForTimeout(1100);assert.match(await video.locator('.vp-time').textContent(),/00:01/);assert.ok((await video.locator('.vp-caption').textContent()).length);await video.close();});
 await check('First screenshot automatically fills PRD scenes and preserves edited narration',async()=>{await page.locator('[data-scene-field="narration"]').fill('선생님이 수정한 대본입니다.');await page.locator('[data-step="3"]').click();const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=640;c.height=360;c.getContext('2d').fillRect(0,0,640,360);return c.toDataURL();});const file=path.join(out,'screen.png');fs.writeFileSync(file,Buffer.from(png.split(',')[1],'base64'));await page.locator('#image-files').setInputFiles(file);await page.waitForFunction(()=>YVM.store.get().images.length===1);const p=await page.evaluate(()=>YVM.store.get());assert.ok(p.scenes.every(s=>s.imageId===p.images[0].id));assert.equal(p.scenes[0].narration,'선생님이 수정한 대본입니다.');});
 await check('Opening PRD does not overwrite existing work',async()=>{const id=await page.evaluate(()=>YVM.store.get().id);await page.locator('[data-step="1"]').click();await page.locator('#prd-import').click();await page.locator('#prd-file').setInputFiles(path.join(out,'quiz.md'));await page.locator('#prd-create').waitFor();await page.locator('#prd-title').fill('새 PRD 영상');await page.locator('#prd-create').click();assert.notEqual(await page.evaluate(()=>YVM.store.get().id),id);const old=await page.evaluate(id=>YVM.store.all().find(p=>p.id===id),id);assert.equal(old.scenes[0].narration,'선생님이 수정한 대본입니다.');assert.equal(old.images.length,1);});
 for(const name of ['quiz.txt','quiz.md','quiz.json','quiz.docx','quiz.hwpx','stored.docx','linebreak.docx','utf16.txt']){
  await check('Upload '+name+' extracts valid text and excludes future features',async()=>{await page.locator('[data-step="1"]').click();await page.locator('#prd-import').click();await page.locator('#prd-file').setInputFiles(path.join(out,name));await page.locator('#prd-create').waitFor();assert.equal(await page.locator('#prd-title').inputValue(),'별빛 퀴즈');assert.equal(await page.locator('#prd-duration').inputValue(),'45');assert.ok(!(await page.locator('#prd-features').inputValue()).includes('AI'));await page.locator('#prd-create').click();await page.waitForSelector('#preview');assert.equal(await page.evaluate(()=>YVM.store.get().prd.filename),name);});
 }
 await check('Invalid, empty, unsupported and oversized files fail visibly',async()=>{await page.locator('[data-step="1"]').click();await page.locator('#prd-import').click();for(const name of ['broken.docx','empty.txt','file.pdf']){await page.locator('#prd-file').setInputFiles(path.join(out,name));await page.waitForFunction(()=>!document.querySelector('#prd-error').hidden);assert.ok(await page.locator('#prd-result').isHidden());}const message=await page.evaluate(async()=>{try{await YVM.readPRDFile(new File([new Uint8Array(2*1024*1024+1)],'big.txt'));}catch(err){return err.message;}});assert.match(message,/2MB/);});
 await check('Drop zone accepts a text file and creates a review',async()=>{await page.evaluate(text=>{const transfer=new DataTransfer();transfer.items.add(new File([text],'drop.txt',{type:'text/plain'}));document.querySelector('#prd-drop').dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));},text);await page.locator('#prd-create').waitFor();assert.equal(await page.locator('#prd-title').inputValue(),'별빛 퀴즈');});
 await check('Edited source hides stale extraction until reanalysis',async()=>{await page.locator('#prd-text').fill(text.replace('별빛 퀴즈','태양 퀴즈'));assert.ok(await page.locator('#prd-result').isHidden());await page.locator('#prd-analyze').click();assert.equal(await page.locator('#prd-title').inputValue(),'태양 퀴즈');});
 await check('A pending file read cannot replace a newly selected input example',async()=>{await page.evaluate(()=>{window.originalPRDReader=YVM.readPRDFile;YVM.readPRDFile=()=>new Promise(resolve=>{window.completePRDRead=resolve;});});await page.locator('#prd-file').setInputFiles(path.join(out,'quiz.md'));await page.locator('#prd-sample').click();await page.evaluate(()=>{window.completePRDRead('프로젝트명: 지연된 파일\n한 줄 소개: 뒤늦게 완료한 파일 본문입니다.');YVM.readPRDFile=window.originalPRDReader;});assert.ok((await page.locator('#prd-text').inputValue()).startsWith('# 별빛 퀴즈 PRD'));assert.ok(await page.locator('#prd-result').isHidden());assert.ok(await page.locator('#prd-analyze').isEnabled());});
 await check('Pasted markup remains inert in extraction and preview',async()=>{await page.locator('#prd-text').fill(text.replace('별빛 퀴즈','<img src=x onerror="window.prdInjected=true">'));await page.locator('#prd-analyze').click();assert.equal(await page.evaluate(()=>window.prdInjected),undefined);assert.equal(await page.locator('#prd-result img').count(),0);});
 await check('Tablet dialog remains within viewport and controls are accessible',async()=>{await page.setViewportSize({width:1024,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'prd-tablet.png')});await page.locator('#close-modal').click();await page.locator('[data-step="1"]').click();assert.ok(await page.locator('#prd-import').isVisible());await page.setViewportSize({width:1440,height:1100});});
 await check('No page errors, console errors or external requests',async()=>{assert.deepEqual(errors,[]);assert.deepEqual(external,[]);});
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({date:new Date().toISOString(),checks:results,passed:results.length,errors,externalRequests:external},null,2));console.log(results.length+' PRD browser checks passed.');
})().catch(err=>{console.error(err);process.exitCode=1;}).finally(async()=>browser?.close());
